server:
  port: 9001

cloud:
  aws:
    stack:
      auto: false
    region:
      static: <reagion>
      auto: false
    end-point:
      uri: <url of the queue>
    credentials:
      access-key: <access-key>
      secret-key: <secret-key>
