server:
  port: ${SERVER_PORT:9001}

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
      auto: false
    end-point:
      uri: ${CLOUD_AWS_END_POINT_URI}
    credentials:
      use-default-aws-credentials-chain: false
      instance-profile: false
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
